### ISSUE TITLE
Package missing 

### ISSUE THREAD

**Issue by ziorick** [fadilfadz01/Universal_Updater#4]
Hi!
While using to update my Lumia 640, the 2.1 beta works fine, the new 2.5.x request a missing package win32.registry. Can you help me?

**Comment by hooddy** [comment]
the same on other phone 
Error:
  An assembly specified in the application dependencies manifest (Universal Updater.deps.json) was not found:
    package: 'Microsoft.Win32.Registry', version: '5.0.0'
    path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'

**Comment by shMatrix** [comment]
Same for me
desktop win8.1x64

**Comment by undermuz** [comment]
same error win11x64

**Comment by Elix-g** [comment]
since not any reply for over two month, can we assume this project is dead?

**Comment by Symnok** [comment]
Same issue.
"Error:
An assembly specified in the application dependencies manifest (Universal Updater.deps.json) was not found:
package: 'Microsoft.Win32.Registry', version: '5.0.0'
path: 'runtimes/win/lib/netstandard2.0/Microsoft.Win32.Registry.dll'"

**Comment by fadilfadz01** [comment]
It will be fixed soon. Until then use the old version.
