### ISSUE TITLE
I get 800b010a on my lumia 625 (RM-941) when upgrading to 10.0.10549.4

### ISSUE THREAD

**Issue by Intelinsidecom** [fadilfadz01/Universal_Updater#7]
[GetDuLogs-{299338D7-E9AD-4D02-BD74-B341894FDEEF}.zip](https://github.com/fadilfadz01/Universal_Updater/files/13267668/GetDuLogs-.299338D7-E9AD-4D02-BD74-B341894FDEEF.zip)

**Comment by fadilfadz01** [comment]
You have to use this patch:
https://github.com/fadilfadz01/Astoria-Patch
